version: "3.3"
services:
  cli:
    build: cli
    # image: warr/php-cli
    # command: crond -f -l 8  #activate cronjob
    volumes:
      - ..:/workspaces/laravel
      - ./ssh:/home/user/.ssh
      - ./cli/cron:/etc/periodic/1min
  # database
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example456
      MYSQL_DATABASE: laravel-app

  #simple database manager
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  
  # redis:
  #   image: redis:6.2-alpine